### ISSUE TITLE
update python implementation

### ISSUE THREAD

**Issue by vitoller** [objectbox/objectbox-python#2]
It would be great to be able to use ObjectBox in Python.

I tried to add relations and querybuilder, but noticed that the Python examples are based on an old version of objectbox.

what are the changes to objectbox since then?

The proposal is to:
* update python bindings
* add relations
* add querybuilder

Thanks

**Comment by vaind** [comment]
The new v0.2.0 release updates to the latest c-api v0.10.0, with some other additions: [release notes](https://github.com/objectbox/objectbox-python/releases/tag/v0.2.0).

objectbox-python is looking for contributors, so if you're willing, please have a look at the issues and [CONTRIBUTING.md](https://github.com/objectbox/objectbox-python/blob/main/CONTRIBUTING.md)

e.g. issues to add relations #7 and queries #3 are ready to work on.

Closing this issue, the detailed discussions should go to appropriate followup issues
