### ISSUE TITLE
C-API return error handling

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-python#6]
Error codes returned from the C-API (type `obx_err`) are currently ignored, see e.g. `Box::is_empty()` calling `obx_box_is_empty()`. C function `obx_box_is_empty()` returns error code, which, if not zero, should raise an exception with the error text. 

As an example, see functions in [helpers.dart](https://github.com/objectbox/objectbox-dart/blob/main/lib/src/bindings/helpers.dart) and how it's used in dart's [`Box::isEmpty()`](https://github.com/objectbox/objectbox-dart/blob/main/lib/src/box.dart#L261)

**Comment by mytlogos** [comment]
This issue should have been fixed at the earliest in b4686068 and is currently implemented via ctypes func.errcheck Callback.
Could you please close this issue as fixed?
